version: 1
update_configs:
    - package_manager: "php:composer"
      directory: "/"
      update_schedule: "live"
      default_labels:
          - "Dependencies ğŸ“¦"
          - "PHP ğŸ˜"
      version_requirement_updates: "widen_ranges"
      automerged_updates:
          - match:
                dependency_type: "all"
                update_type: "semver:minor"
          - match:
                dependency_type: "all"
                update_type: "semver:patch"
